# This file is for local development only
version: '3.7'

services:
  app:
    build: .
    command: >
        flask --app main run --debug
        --host 0.0.0.0 --port 5000
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    env_file:
      - .env
